### ISSUE TITLE
Version Checking Issues

### ISSUE THREAD

**Issue by CasDragon** [Pathfinder-WOTR-Modding-Community/ModFinder#103]
Currently in the unreleased version of the client,  there's a couple issues with version checking.

This issue is only being posted so I don't forget to look into it, and/or if someone is building Modfinder's client manually for some reason?

1. `1.0.3a` is considered older than `1.0.3` 
    * ![2024-06-20 19 54 11 - MainWindow](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/assets/91767316/c51101b3-e6e7-4088-ade3-0f2671aaa5f2)
    * Probably an easy fix

2. Version checking for dependencies seems to also be broken
    * ![2024-06-20 19 53 21 - MainWindow](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/assets/91767316/f81e7549-2a66-4a95-84f6-78d0b5a7175d)

**Comment by CasDragon** [comment]
Oh right, I can't assign myself to this :owlcat_laugh:

**Comment by BarleyFlour** [comment]
Fixed it in the PR I linked.
