### ISSUE TITLE
Weapon Focus Plus update available after update

### ISSUE THREAD

**Issue by Quitch** [Pathfinder-WOTR-Modding-Community/ModFinder#110]
# Description

Weapon Focus Plus is showing as having an update available from v1.2.3 to v1.2.3.2, even after updating.

# Steps to Recreate

1. Install Weapon Focus Plus
2. Click Update

# Notes

Uninstalling and reinstalling the mod did not work.
Flushing the cache did not work.

**Comment by CasDragon** [comment]
You updated correctly, Vek just didn't update the Info.json file in the mod itself. Nothing we can do to fix it, it's on Weapon Focus Plus's end

If you want to stop having it annoy you, click the "..." icon next to it, click "Open Folder", and then in the folder, open the "Info.json", and at the end of the version number, add a `.2` to it.
