### ISSUE TITLE
Wrong dates

### ISSUE THREAD

**Issue by Hillgrove** [Pathfinder-WOTR-Modding-Community/ModFinder#115]
First time using your mod (looks great btw)..

The dates seem wrong though:

![image](https://github.com/user-attachments/assets/d4cd1e3e-1afa-4a08-9ef6-6b8186bedcc3)

last updated: Jun 13, 2024

but according to the github for the mod it hasn't been updated in several years:

![image](https://github.com/user-attachments/assets/0403ddee-4fae-41db-a6b4-724e88460bc2)

**Comment by WittleWolfie** [comment]
It's based on the release date: https://github.com/Balkoth-dev/BuffBot-Wrath/releases. Probably Balkoth didn't push.
