### ISSUE TITLE
Steamdeck linux install

### ISSUE THREAD

**Issue by violencepierre** [Pathfinder-WOTR-Modding-Community/ModFinder#119]
hey bros any tips how to get this running on steamdeck? I use proton experimental for wrath and was able to install UMM in there, but running modfinder would tell me UMM is not yet installed

**Comment by CasDragon** [comment]
Modfinder is a Windows based program. As a result of that, we can't really provide support for Linux based systems like the SteamDeck. WINE/Proton do their best to translate between the program and the operating system, but unfortunately there are issues like this.
