### ISSUE TITLE
Failed to check UMM state. Make sure UMM is installed & launch WOTR once

### ISSUE THREAD

**Issue by ghfromhougang** [Pathfinder-WOTR-Modding-Community/ModFinder#121]
I tried to run ModFinder but got this error message instead "Failed to check UMM state. Make sure UMM is installed & launch WOTR once"

Dunno if this affects the ModFinder, but when I start UMM 0.31.1 ally my installed mods are not listed except for 1 SpeechMod, the status is blank; if I click "Check updates" it just gets stuck on "Checking mod updates"

[Log.txt](https://github.com/user-attachments/files/18268937/Log.txt)

**Comment by CasDragon** [comment]
As said on Discord, it appears your UMM isn't installed correctly, and that clicking the Uninstall and then Install button in the UMM installer would fix your issue.
