### ISSUE TITLE
Add notify about compatible/new version of the mod button

### ISSUE THREAD

**Issue by Majber** [Pathfinder-WOTR-Modding-Community/ModFinder#17]
Like in title it will be cool if you would "add notify about compatible/new version of the mod button" ( if we want the mod but we want new version or version that will be comaptible, like wishlist/follow from steam)

**Comment by Majber** [comment]
I dont mean sth big as desktop notifications . Yes sth like dialog when you load ModFinder would be enough, even sth like red lettered "this mod isnt compatible with your Wrath version" or sth like that for compatibility. And for "new version of the mod" just sth like, "last updated x hours/days ago" near version of the mod would be sufficient I think. Nothing fancy.

**Comment by WittleWolfie** [comment]
Yeah we can probably do that. In general I'd like to rework the UI a bit to make it obvious when:

* There's a problem with a mod (bad game version, missing pre-req)
* There's an update available

Probably the default sort + alert icons will be sufficient.

**Comment by Majber** [comment]
Yes, that would be great :)

**Comment by WittleWolfie** [comment]
Oh yeah this is done now. Status icons (quest stamps from the game) indicate status and the default sort shows actionable (missing pre-req for update available) first.
