### ISSUE TITLE
Name: Quick Cast goes to WIT https://github.com/thehambeard/WIT

### ISSUE THREAD

**Issue by Griznah** [Pathfinder-WOTR-Modding-Community/ModFinder#23]
As title.
![image](https://user-images.githubusercontent.com/1106853/190490160-730f8500-ca66-4c9f-a1eb-0be1c599c57d.png)

**Comment by WittleWolfie** [comment]
This is actually correct, Quick Cast was renamed to WIT aka WotR Inventory Tweak. I added a note to the name to clarify.
