### ISSUE TITLE
virus detection flag

### ISSUE THREAD

**Issue by philiphau** [Pathfinder-WOTR-Modding-Community/ModFinder#24]
Love the idea!
getting these flags on virus scanning
![image](https://user-images.githubusercontent.com/38157694/192354875-56a05877-99ca-4df7-856f-fd73d77c9242.png)
![image](https://user-images.githubusercontent.com/38157694/192354976-e0b5bc57-11d1-40b9-a8b3-886a35bbc19b.png)

**Comment by WittleWolfie** [comment]
Yeah, we looked into it but there's not really anything we can do about it. I'll try to remember to post the hash on release but otherwise there's no good process for us to clear these.
