### ISSUE TITLE
modfinder failing to check installed mods

### ISSUE THREAD

**Issue by RainbowRenegade** [Pathfinder-WOTR-Modding-Community/ModFinder#41]
after updating to the most recent patch, 3.6 I believe, I came to find that half the mods I was using were unusable, and attempting to redownload them through the mod manager gave me an error, and a text file that I have zero ability to comprehend. heres the file, any help would be greatly appreciated 
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/10250681/Log.txt)
heres the twext file, let me know if you need anything else

**Comment by WittleWolfie** [comment]
Delete this folder: E:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods\Download_This_RespecWrath
