### ISSUE TITLE
Disabling Template mods is broken 

### ISSUE THREAD

**Issue by CasDragon** [Pathfinder-WOTR-Modding-Community/ModFinder#44]
Disabling Template mods in Modfinder doesn't disable them. The UI will show going from enabled to disabled, but upon restarting Modfinder, they will show as enabled, and are still enabled in OwlcatModificationManagerSettings.json

Modfinder version: 1.3.7

**Comment by WittleWolfie** [comment]
Should be fixed in 1.3.8
