### ISSUE TITLE
Incorrect MewsiferConsole release filter

### ISSUE THREAD

**Issue by microsoftenator2022** [Pathfinder-WOTR-Modding-Community/ModFinder#48]
Currently it is not possible to install MewsiferConsole.
The release filter is currently: `MewsiferConsole\\.[\\d+]` which does not match the current release asset "MewsiferConsole.zip" but (somehow) *does* match (and incorrectly dowloads) "MewsiferConsole.Menu.zip"

The filter should probably be something like `MewsiferConsole\\.(\\d+\\.)*$` (adding the extension before $ if necessary)

**Comment by WittleWolfie** [comment]
Thanks. Fixed.
