### ISSUE TITLE
Add Damage Breakdown and Weapon Focus Plus

### ISSUE THREAD

**Issue by Vek17** [Pathfinder-WOTR-Modding-Community/ModFinder#5]
Weapon Focus Plus - Weapon Focus Plus allows you to use fighter weapon group based weapon focus instead of picking a single weapon.
https://github.com/Vek17/WrathMods-WeaponFocusPlus
Damage Breakdown - Adds a breakdown for damage bonuses to Pathfinder: Wrath of the Righteous.
https://github.com/abias1122/WOTRDamageBreakdown

**Comment by WittleWolfie** [comment]
Done. Let me know if there's any issues w/ them.
