### ISSUE TITLE
May I suggest something?

### ISSUE THREAD

**Issue by ssebaa** [Pathfinder-WOTR-Modding-Community/ModFinder#50]
Hey, I love your project and it's lovely to be able to install mods from the tool. Would you mind to add some regularly updated mods?

I would like to suggest an isekai mod: [https://github.com/JohN100x1/WOTR_IsekaiMod](url)

Of course the choice is quite personal... however I believe they are great mods and they deserve more attention ;)
I would be grateful if it would be possible to add this mod.

Have a nice day!
Seba

**Comment by WittleWolfie** [comment]
It should be supported now, re-open if you have any issues.

**Comment by ssebaa** [comment]
I noticed it when opened to check after an update a few days ago. Amazing thanks!
