### ISSUE TITLE
Unable to open ModFinder（cn version）

### ISSUE THREAD

**Issue by AitaiSu** [Pathfinder-WOTR-Modding-Community/ModFinder#52]
tks for author，but i couldn't run it.
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/10985631/Log.txt)

**Comment by WittleWolfie** [comment]
Log shows a network error. It's failing to connect to GitHub to fetch the manifest. Some other users suggested it could be an issue w/ your VPN configuration.
