### ISSUE TITLE
I can't install it into UMM

### ISSUE THREAD

**Issue by zagaroth** [Pathfinder-WOTR-Modding-Community/ModFinder#53]
When I dragging the modfinder.zip file to UMM, I get the message:

>[10:10 PM] ModFinder.zip is not supported.

I also tried running UMM as administrator and got the same results. I also tried using the "install mod" button instead of dragging and dropping.

**Comment by WittleWolfie** [comment]
ModFinder is not a mod, it's a standalone executable. You just run it.
