### ISSUE TITLE
Failed to check UMM state

### ISSUE THREAD

**Issue by exartha** [Pathfinder-WOTR-Modding-Community/ModFinder#59]
When I open modfinder application I always get this error
Here is the log
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/11778598/Log.txt)

**Comment by WittleWolfie** [comment]
Your UMM `Params.xml` file seems to be corrupted. I'd try re-installing UnityModManager.

**Comment by WittleWolfie** [comment]
Alternatively, share `D:\Artha\Games\PC\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\UnityModManager\Params.xml` and I can investigate further.
