### ISSUE TITLE
Failed to initialize main window

### ISSUE THREAD

**Issue by meetblake** [Pathfinder-WOTR-Modding-Community/ModFinder#62]
Can't open ModFinder 
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/12088176/Log.txt)

[7/19 02:39:33][E] Failed to initialize main window.
[7/19 02:39:33][E] System.InvalidOperationException: Failed to compare two elements in the array.

**Comment by WittleWolfie** [comment]
It looks like you have an invalid mod. This is throwing an exception because you have a mod w/ no name?

**Comment by meetblake** [comment]
> It looks like you have an invalid mod. This is throwing an exception because you have a mod w/ no name installed?

Thanks, I solved it.
