### ISSUE TITLE
Add compatibility with game version /info

### ISSUE THREAD

**Issue by Majber** [Pathfinder-WOTR-Modding-Community/ModFinder#8]
If mod have info about with what version of game is compatible it would be cool to see it.

**Comment by WittleWolfie** [comment]
Agreed. We're discussing it on Discord.

My plan is to:

1. Flag if there's a game version incompatibility
2. Add a rollback function

**Comment by WittleWolfie** [comment]
Rollback is already in, closing this out because game version incompatibility relies on mods actually specifying which they basically never do.
