### ISSUE TITLE
Failed to check installed mods

### ISSUE THREAD

**Issue by greyvoice** [Pathfinder-WOTR-Modding-Community/ModFinder#86]
i keep getting the Failed to check installed mods error message and i wasn't getting it before, what can i do to make this go away? from the looks of it i don't have any duplicate files...
 i am completely lost here it just randomly started. I'm afraid the program won't work as intended and its annoying to boot. any help would be greatly appreciated!
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/13932882/Log.txt)

**Comment by WittleWolfie** [comment]
From the log:

> System.ArgumentException: An item with the same key has already been added. Key: RanEpilogue-UMM

The log doesn't show the folder, but it seems like you have two copies of RanEpilogue installed (it may be different named folders). Deleting both and reinstalling through ModFinder should resolve it. If not, let us know!
