### ISSUE TITLE
Craftmaster

### ISSUE THREAD

**Issue by skawhach** [Pathfinder-WOTR-Modding-Community/ModFinder#90]
https://github.com/magicskysword/CraftMaster seems to have updated the files themselves, but the DLL seems to still be outdated. If there's something I can do myself to fix it, please let me know. (the mod will get installed fine, and it's available before loading a game, but as soon as a save is loaded, the UMM menu logs show several errors. 
[Player.log](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/14395168/Player.log)

The mod folder also looks suspiciously empty compared to other mods, containing only a localisation folder and a dll. I've tried both installing with a ZIP and directly from Modfinder.

**Comment by WittleWolfie** [comment]
Looks like craftmaster is no longer supported.
