### ISSUE TITLE
Server issue?

### ISSUE THREAD

**Issue by Kolya404** [Pathfinder-WOTR-Modding-Community/ModFinder#98]
[Log.txt](https://github.com/user-attachments/files/15858246/Log.txt)

I can't understand, what actualy reason.
There part, which make me think it's connection problemm: System.AggregateException: One or more errors occurred. (Этот хост неизвестен[unknown host]. (raw.githubusercontent.com:443))

But it's never happen before.
(Sory, I can be bad at english)

**Comment by Kolya404** [comment]
Problemm is solved. It's were one of modds.

**Comment by WittleWolfie** [comment]
Glad you resolved it.
